### ISSUE TITLE
Fails to compile in Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by Andrew-F-in-Australia** [ashaffer/rt3573sta#11]
Have uploaded details etc... here
http://ubuntuforums.org/showthread.php?t=2228347&p=13043330#post13043330

Is this an easy fix/bug? - am happy to assist with faultfinding.

AF

**Comment by fthamura** [comment]
i dont have wlan4 run in my machine

#lsusb

lsusb
Bus 002 Device 004: ID 046d:c31c Logitech, Inc. Keyboard K120 for Business
Bus 002 Device 003: ID 0458:012b KYE Systems Corp. (Mouse Systems) 
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 148f:7601 Ralink Technology, Corp.

**Comment by fthamura** [comment]
In file included from /root/rt3573sta/include/os/rt_linux.h:43:0,
                 from /root/rt3573sta/include/rtmp_os.h:42,
                 from /root/rt3573sta/include/rtmp_comm.h:56,
                 from /root/rt3573sta/os/linux/../../os/linux/sta_ioctl.c:33:
/root/rt3573sta/os/linux/../../os/linux/sta_ioctl.c: In function ‘rt_ioctl_giwscan’:
include/net/iw_handler.h:542:9: warning: array subscript is below array bounds [-Warray-bounds]
   memcpy(stream + point_len, extra, iwe->u.data.length);
         ^
  CC [M]  /root/rt3573sta/os/linux/../../os/linux/rt_linux.o
/root/rt3573sta/os/linux/../../os/linux/rt_linux.c: In function ‘__RtmpOSFSInfoChange’:
/root/rt3573sta/os/linux/../../os/linux/rt_linux.c:1138:20: error: incompatible types when assigning to type ‘int’ from type ‘kuid_t’
   pOSFSInfo->fsuid = current_fsuid();
                    ^
/root/rt3573sta/os/linux/../../os/linux/rt_linux.c:1139:20: error: incompatible types when assigning to type ‘int’ from type ‘kgid_t’
   pOSFSInfo->fsgid = current_fsgid();
                    ^
make[2]: **\* [/root/rt3573sta/os/linux/../../os/linux/rt_linux.o] Error 1
make[1]: **\* [_module_/root/rt3573sta/os/linux] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.13.0-30-generic'
make: **\* [LINUX] Error 2
root@baremerv:~/rt3573sta#

**Comment by fthamura** [comment]
done can compile. :)

still working to make wifi work.
